# Generated by Django 5.2.6 on 2026-01-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='requestStatus',
            field=models.TextField(default='Pending'),
        ),
    ]
