# Generated by Django 5.2.6 on 2026-01-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_requests_requeststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='requestStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-progress', 'In-progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
