# Generated by Django 5.2.6 on 2026-01-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_requests_requeststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignments',
            name='workStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-progress', 'In-progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
